CREATE OR REFRESH STREAMING TABLE BRONZE_ROAD.CASUALTY_HIST
COMMENT "RAW DATA ABOUT CASUALTY 2017-2022"
AS
SELECT *, current_timestamp() AS LOAD_DATE
FROM STREAM read_files(
  '/Volumes/test/default/road/casualty-data/',
  format => 'csv',
  header => 'true'
);

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.CASUALTY_HIST
AS
SELECT 
  CAST(TRIM(A_YEAR) AS INT) AS YEAR,
  CAST(TRIM(A_REF) AS INT) AS REF,
  CAST(TRIM(V_ID) AS INT ) AS VEHICLE_ID,
  CAST(C_ID AS INT ) AS CASUALTY_ID,
  C_SEX,
  C_CLASS,
  C_AGEGROUP,
  C_SEVER,
  C_LOC,
  C_MOVE,
  C_SCHOOL,
  C_PCV,
  C_PEDINJ,
  C_VTYPE,
  LOAD_DATE
FROM STREAM BRONZE_ROAD.CASUALTY_HIST
WHERE 
  TRIM(A_YEAR) IS NOT NULL
  AND TRIM(A_REF) IS NOT NULL
  AND TRIM(V_ID) IS NOT NULL
;

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.casualty_hist_FACT
COMMENT "FACT TABLE ABOUT CASUALTY 2017-2022";

CREATE FLOW FW_SILVER_CASUALTY_HIST_FACT
AS
AUTO CDC INTO SILVER_ROAD.CASUALTY_HIST_FACT
FROM STREAM SILVER_ROAD.CASUALTY_HIST
KEYS(YEAR, REF, VEHICLE_ID)
SEQUENCE BY LOAD_DATE
;

CREATE OR REFRESH MATERIALIZED VIEW SILVER_ROAD.M_CASUALTY_FACT
COMMENT "EXTENDED DATA ABOUT CASUALTY AND VEHICLE DURING 2017-2022"
AS
SELECT 
  CF.YEAR,
  CF.REF,
  VF.TYPE,
  VF.SEX,
  VF.HIT,
  CF.CASUALTY_ID,
  CF.C_CLASS,
  CF.C_SEX,
  CF.C_SEVER
FROM silver_road.casualty_hist_fact CF 
INNER JOIN silver_road.m_vehicle_fact VF
  ON CF.YEAR = VF.YEAR
  AND CF.REF = VF.REF
  AND CF.VEHICLE_ID = VF.ID
;

CREATE OR REFRESH MATERIALIZED VIEW GOLD_ROAD.M_CASUALTY_CNT
COMMENT "DATA REPRESENTED HOW MANY PEOPLE IN CASUAL NOT DRIVER"
AS
SELECT 
  YEAR,
  REF,
  MAX(TYPE) AS TYPE,
  COUNT(*) AS CNT_CASUALTY
FROM SILVER_ROAD.M_CASUALTY_FACT
WHERE 
  C_CLASS <> 'Driver'
GROUP BY YEAR, REF
HAVING CNT_CASUALTY > 1
;
