CREATE OR REFRESH STREAMING TABLE BRONZE_ROAD.COLLISION_HIST
COMMENT "RAW DATA ABOUT collision 2017-2022"
AS
SELECT *, current_timestamp() AS LOAD_DATE
FROM STREAM read_files(
  '/Volumes/test/default/road/collision-data/',
  format => 'csv',
  header => 'true'
);

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.COLLISION_HIST
AS
SELECT 
  MAKE_DATE(TRIM(A_YEAR), TRIM(A_MONTH), TRIM(A_DAY)) AS DATE,
  A_HOUR || ':' || A_MIN AS TIME,
    CASE A_WKDAY
    WHEN 'MON' THEN 'MONDAY'
    WHEN 'TUE' THEN 'TUESDAY'
    WHEN 'WEN' THEN 'WEDNESDAY'
    WHEN 'THU' THEN 'THURSDAY'
    WHEN 'FRI' THEN 'FRIDAY'
    WHEN 'SAT' THEN 'SATURDAY'
    WHEN 'SUN' THEN 'SUNDAY'
  END AS WEEKDAY,
  CAST(TRIM(A_REF) AS INT) AS REF,
  A_DISTRICT,
  A_TYPE,
  A_VEH AS VEHICLE_ID,
  A_CAS AS C_ID,
  A_SPEED AS SPEED,
  A_JDET,
  A_JCONT,
  A_PEDHUM,
  A_PEDPHYS,
  A_LIGHT,
  A_WEAT,
  A_ROADSC,
  LOAD_DATE
FROM STREAM BRONZE_ROAD.COLLISION_HIST
WHERE 
  TRIM(A_YEAR) IS NOT NULL
  AND TRIM(A_REF) IS NOT NULL
  AND TRIM(A_MONTH) IS NOT NULL
  AND TRIM(A_DAY) IS NOT NULL
;

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.COLLISION_HIST_FACT
COMMENT "CLEAR AND ENRIHED DATA ABOUT COLLISION DURING 2017-2022"
;

CREATE FLOW FW_SILVER_COLLISION_HIST_FACT
AS
AUTO CDC INTO SILVER_ROAD.COLLISION_HIST_FACT
FROM STREAM SILVER_ROAD.COLLISION_HIST
KEYS(DATE, REF)
SEQUENCE BY LOAD_DATE
;

CREATE OR REFRESH MATERIALIZED VIEW GOLD_ROAD.M_COLLISION_SPEED_FACT
COMMENT "DATA REPRESENT MIN AND MAX SPEED ON EVERY DISTRICT DURING 2017-2022 IN NON-BUSINESS DAY"
AS
SELECT 
  trunc(date, 'YYYY') as YEAR,
  A_DISTRICT,
  A_TYPE,
  max(speed) as MAX_SPEED,
  min(speed) as MIN_SPEED
FROM SILVER_ROAD.collision_hist
WHERE 
  upper(A_LIGHT) like 'DAYLIGHT%'
  and WEEKDAY IN ('SUNDAY', 'SATURDAY')
group by YEAR, A_DISTRICT, A_TYPE
;
