CREATE OR REFRESH STREAMING TABLE BRONZE_ROAD.VEHICLE_IND
COMMENT "RAW DATA FOR DIRECTORY OF VEHICLE"
SCHEDULE EVERY 30 DAYS
AS
SELECT 
  COL AS KEY_NAME, 
  DUMMY AS KEY_VALUE,
  NAME AS KEY_DESCRIPTION, 
  current_timestamp() AS LOAD_DATE
FROM STREAM read_files(
  '/Volumes/test/default/road/vehicle-ind/',
  format => 'csv',
  header => 'true'
);

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.VEHICLE_IND_FACT
COMMENT "CLEANED SCD FOR DIRECTORY OF VEHICLE";

CREATE FLOW FW_TO_SILVER_VEHICLE_IND
AS
AUTO CDC INTO SILVER_ROAD.VEHICLE_IND
FROM STREAM BRONZE_ROAD.VEHICLE_IND
KEYS(KEY_NAME, KEY_VALUE)
SEQUENCE BY LOAD_DATE
STORED AS SCD TYPE 2
;