CREATE OR REFRESH STREAMING TABLE BRONZE_ROAD.VEHICLE_HIST
COMMENT "RAW DATA FROM CSV FILE ABOUT VEHICLES 2017-2022"
AS 
SELECT *, current_timestamp() AS LOAD_DATE
FROM STREAM read_files(
  '/Volumes/test/default/road/vehicle-data/',
  format => 'csv',
  header => 'true'
);

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.VEHICLE_HIST
AS 
SELECT 
 A_YEAR AS YEAR,
 TRY_CAST(TRIM(A_REF) AS INT)       AS REF,
 TRY_CAST(TRIM(V_ID) AS INT)        AS ID,
 TRY_CAST(TRIM(V_TYPE) AS INT)      AS TYPE,
 TRY_CAST(TRIM(V_TOW) AS INT)       AS TOW,
 TRY_CAST(TRIM(V_MAN) AS INT)       AS MAN,
 TRY_CAST(TRIM(V_LOC) AS INT)       AS LOC,
 TRY_CAST(TRIM(V_JUNC) AS INT)      AS JUNC,
 TRY_CAST(TRIM(V_SKID) AS INT)      AS SKID,
 TRY_CAST(TRIM(V_HIT) AS INT)       AS HIT,
 TRY_CAST(TRIM(V_LEAVE) AS INT)     AS LEAVE,
 TRY_CAST(TRIM(V_HITOFF) AS INT)    AS HITOFF,
 TRY_CAST(TRIM(V_IMPACT) AS INT)    AS IMPACT,
 TRY_CAST(TRIM(V_SEX) AS INT)       AS SEX,
 TRY_CAST(TRIM(V_AGEGROUP) AS INT)  AS AGEGROUP,
 TRY_CAST(TRIM(V_HITR) AS INT)      AS HITR,
 TRY_CAST(TRIM(V_FORREG) AS INT)    AS FORREG,
 LOAD_DATE
FROM STREAM BRONZE_ROAD.VEHICLE_HIST
WHERE 
  A_YEAR IS NOT NULL 
  AND A_REF IS NOT NULL
  AND V_ID IS NOT NULL
;

CREATE OR REFRESH STREAMING TABLE SILVER_ROAD.VEHICLE_HIST_FACT
COMMENT "FACT FOR VEHICLE HIST"
;

CREATE FLOW FW_SILVER_VEHICLE_HIST_FACT
AS
AUTO CDC INTO SILVER_ROAD.VEHICLE_HIST_FACT
FROM STREAM SILVER_ROAD.VEHICLE_HIST
KEYS(YEAR, REF, ID)
SEQUENCE BY LOAD_DATE
;

CREATE MATERIALIZED VIEW SILVER_ROAD.M_VEHICLE_FACT
AS
SELECT 
  F.YEAR,
  F.ID,
  F.REF,
  D_TOW.KEY_DESCRIPTION AS TOW,
  D_MAN.KEY_DESCRIPTION AS MAN,
  D_LOC.KEY_DESCRIPTION AS LOC,
  D_JUNC.KEY_DESCRIPTION AS JUNC,
  D_SKID.KEY_DESCRIPTION AS SKID,
  D_HIT.KEY_DESCRIPTION AS HIT,
  D_LEAVE.KEY_DESCRIPTION AS LEAVE,
  D_HITOFF.KEY_DESCRIPTION AS HITOFF,
  D_IMPACT.KEY_DESCRIPTION AS IMPACT,
  D_SEX.KEY_DESCRIPTION AS SEX,
  D_AGEGROUP.KEY_DESCRIPTION AS AGEGROUP,
  D_HITR.KEY_DESCRIPTION AS HITR,
  D_FORREG.KEY_DESCRIPTION AS FORREG
FROM SILVER_ROAD.VEHICLE_HIST_FACT F
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_TYPE
  ON F.TYPE = D_TYPE.KEY_VALUE AND LOWER(LOWER(D_TYPE.KEY_NAME)) = 'v_type'
  AND D_TYPE.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_TOW 
  ON F.TYPE = D_TOW.KEY_VALUE AND LOWER(LOWER(D_TOW.KEY_NAME)) = 'v_tow'
  AND D_TOW.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_MAN
  ON F.TYPE = D_MAN.KEY_VALUE AND LOWER(D_MAN.KEY_NAME) = 'v_man'
  AND D_MAN.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_LOC
  ON F.TYPE = D_LOC.KEY_VALUE AND LOWER(D_LOC.KEY_NAME) = 'v_loc'
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_JUNC
  ON F.TYPE = D_JUNC.KEY_VALUE AND LOWER(D_JUNC.KEY_NAME) = 'v_junc'
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_SKID
  ON F.TYPE = D_SKID.KEY_VALUE AND LOWER(D_SKID.KEY_NAME) = 'v_skid'  
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_HIT
  ON F.TYPE = D_HIT.KEY_VALUE AND LOWER(D_HIT.KEY_NAME) = 'v_hit'
  AND D_HIT.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_LEAVE
  ON F.TYPE = D_LEAVE.KEY_VALUE AND LOWER(D_LEAVE.KEY_NAME) = 'v_leave'
  AND D_LEAVE.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_HITOFF
  ON F.TYPE = D_HITOFF.KEY_VALUE AND LOWER(D_HITOFF.KEY_NAME) = 'v_hitoff'
  AND D_HITOFF.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_IMPACT
  ON F.TYPE = D_IMPACT.KEY_VALUE AND LOWER(D_IMPACT.KEY_NAME) = 'v_impact'
  AND D_IMPACT.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_SEX
  ON F.TYPE = D_SEX.KEY_VALUE AND LOWER(D_SEX.KEY_NAME) = 'v_sex'
  AND D_SEX.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_AGEGROUP
  ON F.TYPE = D_AGEGROUP.KEY_VALUE AND LOWER(D_AGEGROUP.KEY_NAME) = 'v_agegroup'
  AND D_AGEGROUP.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_HITR
  ON F.TYPE = D_HITR.KEY_VALUE AND LOWER(D_HITR.KEY_NAME) = 'v_hitr'
  AND D_HITR.`__END_AT` IS NULL
LEFT JOIN SILVER_ROAD.VEHICLE_IND D_FORREG
  ON F.TYPE = D_FORREG.KEY_VALUE AND LOWER(D_FORREG.KEY_NAME) = 'v_forreg'
  AND D_FORREG.`__END_AT` IS NULL;



